Разметка главной страницы
htmlacademy-adaptive/1700741-cat-energy-25 pull request #2
Opened 2022-04-04 04:46 UTC by alenachesnokova

2022-04-05 12:36 UTC, andreysgra requested changes
Файл index.html должен находиться в папке source, а не в корне проекта. Перенесите его туда.

---

Код нужно отформатировать. В VS Code делается сочетанием клавиш `Alt+Shift+F`.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +            <img class="main-header__logo-image" src="image\mobilelogo.svg" width="33,2px" height="36.6px" alt="логотип cat energy"> </a>
1. Размеры изображений в HTML указываются без обозначения единицы измерения.
2. Размеры должны представлять из себя целые числа. Нужно округлять значение до ближайшего целого.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                    <a class="choose-programm__button button" href="/">
Такие же проблемы со слешем в пути к файлу и с размерами изображения.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                        </div>
Лишний закрывающий тег `</div>`.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                        <img class="how-it-work__image" src="image\iconwatch.svg" width="60px" height="60px" alt="Быстрый результат.">
Эти иконки являются декоративными изображениями и добавлять из в разметку не нужно. Для их отображения используется свойство CSS `background-image` (на этом этапе добавлять ничего не нужно, просто удалите `img`).

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +            <div class="invitation__map" width="320px" height="362px"></div>
`width` и `height` атрибуты тега `img`, а у `div` таких атрибутов нет.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +            <button class="navigtion-mobile_toogle" type="button">
Здесь и далее есть ошибки именования классов по БЭМ. Правильность можно проверить в [данном сервисе](https://yoksel.github.io/html-tree/).

`navigtion-mobile_toogle` это класс модификатора блока в стиле Яндекс (одно нижнее подчёркивание), а поскольку по коду видно, что вы используете модификаторы в международном формате (два минуса), то тут банальная опечатка и это класс БЭМ элемента:
```suggestion
            <button class="navigtion-mobile__toogle" type="button">
```

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                        <div class="sistem__icon--slim">
`sistem__icon--slim` класс модификатора, но модификатор не может использоваться самостоятельно, так как он модифицирует свойства класса блока или элемента, поэтому рядом должен быть класс того элемента или блока, который он модифицирует. В данном случае это элемент:
```suggestion
                        <div class="sistem__icon sistem__icon--slim">
```

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                        <div class="sistem__icon--mass">
Здесь такая же ошибка.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                    <li class="sistems_item sistem">
Не хватает одного символа подчёркивания.
```suggestion
                    <li class="sistems__item sistem">
```

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                <ul class="how-it-work_list">
```suggestion
                <ul class="how-it-work__list">
```

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +    <footer class="index-main__main-footer  main-footer">
Класс `index-main__main-footer` указывает, что это элемент блока `index-main`, но блока с таким именем у вас нет. Здесь, кстати и не нужно давать класс элемента футеру. У него есть класс блока `main-footer` и если у футера главной страницы есть какие-то отличия от внутренних страниц, то их нужно будет описать в классе модификатора, то есть в `main-footer--index`.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                <li class="contacts__item"><a class="contacts__link--telegramm" href="/"><span  class="visually-hidden">Telegramm</span></a>
В ссылках на социальные сети использованы классы модификаторов без классов элементов.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +        <!--А можно сделать логотип фоном?-->
Нет, фоном логотип делать не стоит, так как это контентное изображение. [Как отличить контентное изображение от декоративного](https://htmlacademy.ru/blog/boost/frontend/content-or-decor-img).

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +        </p>
Вот это всё одно целое изображение (в фигме нужно объединить слои при экспорте)
![image](https://user-images.githubusercontent.com/17790771/161751741-83a86990-9695-45ea-a9eb-82e59f9fce52.png)
Поэтому текст здесь не в параграфе, а является частью изображения.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +        </nav>
`nav` это тег для указания основной навигации сайта. Странно, что у вас там только кнопка открытия меню. В `nav` нужно добавить меню сайта:
![image](https://user-images.githubusercontent.com/17790771/161752016-8a53b964-ec09-4923-9f7c-0de5acd75462.png)

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +        <article>
Тег `<article>` используется для самодостаточного контента, при переносе которого на другую страницу сайта смысл содержимого не будет оторван от контекста. Хороший пример - карточка товара из каталога. В данном случае этот тег не подходит, так как вы в него поместили фактически весь контент страницы.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                    <H1 class="choose-programm__title">Функциональное питание для котов</H1>
`H1` - название тега заглавными буквами. Так не принято.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                    <a class="choose-programm__button button" href="/">
Есть такой [пункт ТЗ](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-4-2).

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                        <h2 class="sistem__title">похудение</h2>
Нужно соблюдать иерархию заголовков. Если выше находится общий заголовок второго уровня "Системы питания", то подчинённые заголовки должны быть третьего уровня.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                        <h2 class="sistem__title">Набор массы</h2>
Здесь тоже самое.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                <h2 class="visually-hidden">Приципы работы питания CAT ENERGY</h2>
В макете есть заголовок с текстом
![image](https://user-images.githubusercontent.com/17790771/161753260-5d8f9bc2-959e-42d8-90d0-57269a221462.png)
Зачем придумывать свой? 😏

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                        </p>
В общем-то можно избавиться от параграфа, как от лишнего элемента разметки и текст разместить непосредственно в теге `li`.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                    <dd>снижение веса</dd>
`dt` -термин списка описаний, а `dd` само описание. У вас они переставлены местами. По логике должно быть так: термин - "снижение веса", описание - "5 КГ".

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                    <dd>затрачено времени</dd>
Тоже самое.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +                </form>
Нет, форма здесь совсем не нужна. Никакие данные на сервер отправлять не будем. Это просто слайдер "было | стало). Размечается с помощью `div` и кнопок.

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +            <p class="contacts__title contacts-title"><b class="contacts-title__bold">cat</b> energy</p>
Это ссылка с изображением внутри (логотип сайта со ссылкой на главную страницу)
![image](https://user-images.githubusercontent.com/17790771/161754508-ee5ebc27-a014-486a-b14d-4c6bb583fcf0.png)

2022-04-05 12:36 UTC, andreysgra commented on index.html
> +            <a class="contacts__link htmlacademy" href="http://htmlacademy.ru">HTMLACADEMY</a>
Это ссылка с изображением внутри (иконка академии). Кроме того о логотипе есть такой [пункт ТЗ](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-3-8).

2022-04-05 14:32 UTC, andreysgra requested changes

2022-04-05 14:32 UTC, andreysgra commented on index.html
> +            <img class="main-header__logo-image" src="image\mobilelogo.svg" width="33,2px" height="36.6px" alt="логотип cat energy"> </a>
В пути к файлам должен использоваться обычный слеш, а не обратный. Должно быть так:
```suggestion
            <img class="main-header__logo-image" src="image/mobilelogo.svg" width="33,2px" height="36.6px" alt="логотип cat energy"> </a>
```

2022-04-09 04:49 UTC, alenachesnokova commented on index.html
> +                    <a class="choose-programm__button button" href="/">
Форматирование сбивается при сохранении, почему-то... Остальное поправила

2022-04-09 04:55 UTC, alenachesnokova commented on index.html
> +        </nav>
Не знаю, где брать дизайн меню, в фигме его нет. Добавила списком

2022-04-09 05:01 UTC, alenachesnokova commented on index.html
> +        <article>
А может заголовок h1 быть вне article?

2022-04-09 17:45 UTC, andreysgra commented on index.html
> +        </nav>
Есть же соответствующий фрейм в макете:
![image](https://user-images.githubusercontent.com/17790771/162585496-9741cffd-3738-4846-a446-22f0b7440f6f.png)

2022-04-09 17:52 UTC, andreysgra commented on source/index.html
> +            <ol class="navigation-mobile__list">
`ol` это нумерованный список, а так как порядок элементом нам здесь не важен, то использовать нужно ненумерованный список `ul`.

2022-04-09 17:52 UTC, andreysgra commented on index.html
> +        <article>
Конечно может быть! `h1` обязательно должен присутствовать на странице. В каком теге его размещать не столь важно, главное, чтобы соблюдалась иерархия заголовков - `h2` не может идти раньше, чем `h1`.

Раньше считалось, что на странице должен быть только один `h1`, сейчас допускается использование нескольких заголовков первого уровня, но только внутри `article`, но я бы советовал всё же внутри `article` использовать `h2`, если `h1` уже есть в другой части страницы.

2022-04-09 18:01 UTC, andreysgra requested changes

2022-04-09 18:01 UTC, andreysgra commented on source/index.html
> +        <article>
Вы пометили замечание как исправленное, но не убрали `article` со страницы.

2022-04-09 18:01 UTC, andreysgra commented on source/index.html
> +                <a class="choose-programm__button button" href="/">
Ещё раз напомню про этот [пункт ТЗ](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-4-2): ссылка должна вести на страницу формы сайта.

2022-04-09 18:01 UTC, andreysgra commented on source/index.html
> +                    <span class="example-range__description">Было</span>
Было | Стало по сути интерактивные элементы, поэтому нужно использовать `<button type="button">`, а не `span`.

2022-04-09 18:01 UTC, andreysgra commented on source/index.html
> +                    <dd class="results_value">60 ДНЕЙ</dd>
Ну здесь у вас банальные опечатки в названии класса. Правильно вот так:
```suggestion
                    <dd class="results__value">5 КГ</dd>
                    <dt class="results__characteristic">затрачено времени</dt>
                    <dd class="results__value">60 ДНЕЙ</dd>
```

2022-04-10 20:04 UTC, andreysgra requested changes

2022-04-10 20:04 UTC, andreysgra commented on source/index.html
> +        git
Строка лишняя.

2022-04-10 20:04 UTC, andreysgra commented on Readme.md
> +* Наставник: [Андрей Грачев](https://htmlacademy.ru/profile/id252055)git.
```suggestion
* Наставник: [Андрей Грачев](https://htmlacademy.ru/profile/id252055).
```
Вот так будет лучше 😏

2022-04-11 19:14 UTC, merged